# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wire.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwire.proto\x12\rbidirectional\"9\n\x04Text\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"=\n\x07\x41\x63\x63ount\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\nconnection\x18\x03 \x01(\t\"&\n\x05Query\x12\r\n\x05match\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\"\x14\n\x04List\x12\x0c\n\x04list\x18\x01 \x01(\t\"\x15\n\x03Res\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x06\n\x04Void2\x8a\x02\n\rBidirectional\x12\x37\n\nServerSend\x12\x13.bidirectional.Text\x1a\x12.bidirectional.Res\"\x00\x12\x42\n\x12\x43hangeAccountState\x12\x16.bidirectional.Account\x1a\x12.bidirectional.Res\"\x00\x12?\n\x0c\x43lientStream\x12\x16.bidirectional.Account\x1a\x13.bidirectional.Text\"\x00\x30\x01\x12;\n\x0cListAccounts\x12\x14.bidirectional.Query\x1a\x13.bidirectional.List\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wire_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXT._serialized_start=29
  _TEXT._serialized_end=86
  _ACCOUNT._serialized_start=88
  _ACCOUNT._serialized_end=149
  _QUERY._serialized_start=151
  _QUERY._serialized_end=189
  _LIST._serialized_start=191
  _LIST._serialized_end=211
  _RES._serialized_start=213
  _RES._serialized_end=234
  _VOID._serialized_start=236
  _VOID._serialized_end=242
  _BIDIRECTIONAL._serialized_start=245
  _BIDIRECTIONAL._serialized_end=511
# @@protoc_insertion_point(module_scope)
